version: '3'

services:
  saml-sp:
    build:
      context: "./"
      dockerfile: Dockerfile
    env_file:
      - "./.env"
    container_name: python3-saml-sp
    command: >
      bash -c "apachectl -D FOREGROUND"
    ports:
      - 50443:443
    # volumes:
    #   - ./demo-django:/var/python3-saml/demo-django
